import Navbar from "@/components/Navbar";
import "./globals.css";
import { Inter } from "next/font/google";
import { NextAuthProvider } from "./Providers";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>

        <NextAuthProvider>
        <Navbar className="fixed top-0 left-0 right-0 z-50 bg-white shadow-md" />

          <div className=" mx-auto">
           {/* Fixed navbar with shadow */}
          {children}
          </div>
        </NextAuthProvider>
      </body>
    </html>
  );
}
